### ISSUE TITLE
忽略回收站内的应用

### ISSUE THREAD

**Issue by YuLun-bili** [ShirasawaSama/CefDetector#10]

**Comment by ShirasawaSama** [comment]
回收站内的路径是什么呢？

**Comment by YuLun-bili** [comment]
就是我拿这个扫出来4个没卸载掉的罗技的应用（也不知道是啥），没找到卸载方式就直接扔回收站了，没清空的时候还是能扫到。路径就是$recyclebin下的

**Comment by ShirasawaSama** [comment]
能把路径复制一下或者截个图么，Everything里边搜

**Comment by YuLun-bili** [comment]
类似这样

![image](https://user-images.githubusercontent.com/70589524/204294735-da9c46dd-b5a9-4b63-b42a-b2724ce6a359.png)

![image](https://user-images.githubusercontent.com/70589524/204295097-0fc37b61-006b-477e-81cb-1a2be284e26a.png)

**Comment by ShirasawaSama** [comment]
0.0.1 已忽略回收站和OneDrive下的文件
