### ISSUE TITLE
建议新增扫描Microsoft Edge Webview2

### ISSUE THREAD

**Issue by KormiMeiko** [ShirasawaSama/CefDetector#12]
如题。
你 懂 得（）

**Comment by ShirasawaSama** [comment]
没法检测，因为它不生成相关的文件，它压根就是只调用系统的API

**Comment by KormiMeiko** [comment]
> 

最近拿WPF和Winform试了一下，会生成

Microsoft.Web.WebView2.Core.dll

Microsoft.Web.WebView2.WinForms.dll

Microsoft.Web.WebView2.Wpf.dll

WebView2Loader.dll

**Comment by ShirasawaSama** [comment]
tauri、DeakGap这种呢

**Comment by KormiMeiko** [comment]
> tauri、DeakGap这种呢

没试过唉😂

**Comment by ShirasawaSama** [comment]
这些个别的基于WebView2.0的看了一下基本都是只有一个20多MB的exe，最多再有个dll
