### ISSUE TITLE
电脑了装了软件扫不出来

### ISSUE THREAD

**Issue by huchenghe001** [ShirasawaSama/CefDetector#13]
![QQ截图20221129231755](https://user-images.githubusercontent.com/106022493/204568468-54ef6f04-c223-4bbd-ada7-599927581b00.png)

**Comment by ShirasawaSama** [comment]
有没有安装Everything?

**Comment by huchenghe001** [comment]
> 有没有安装Everything?

我电脑上打底得有edge吧

**Comment by ShirasawaSama** [comment]
你得先装了Everything才能扫描，因为这个程序就是基于Everything的扫描功能来设计的: https://www.voidtools.com/zh-cn/downloads/

**Comment by ShirasawaSama** [comment]
事实上如果你把窗口全屏了它就会提示让你安装Everything

**Comment by huchenghe001** [comment]
> 事实上如果你把窗口全屏了它就会提示让你安装Everything
装了显示130个
