### ISSUE TITLE
好像windows 7即便是有cef也掃描不出來

### ISSUE THREAD

**Issue by ghost** [ShirasawaSama/CefDetector#14]
如題

**Comment by ShirasawaSama** [comment]
有安装everything吗？

**Comment by ghost** [comment]
> 有安装everything吗？

裝了，還是沒有

**Comment by ShirasawaSama** [comment]
要不试试electron版本 https://github.com/ShirasawaSama/CefDetectorX

**Comment by ghost** [comment]
> 要不试试electron版本 https://github.com/ShirasawaSama/CefDetectorX

然后它的也不行😂

**Comment by ShirasawaSama** [comment]
> > 要不试试electron版本 https://github.com/ShirasawaSama/CefDetectorX
> 
> 然后它的也不行😂

Electron版本可以打开控制台，看看有报错么

**Comment by ghost** [comment]
> > > 要不试试electron版本 https://github.com/ShirasawaSama/CefDetectorX
> > 
> > 
> > 然后它的也不行😂
> 
> Electron版本可以打开控制台，看看有报错么

不行吧，这个我按了F12没反应

**Comment by ShirasawaSama** [comment]
> > > > 要不试试electron版本 https://github.com/ShirasawaSama/CefDetectorX
> > > 
> > > 
> > > 然后它的也不行😂
> > 
> > 
> > Electron版本可以打开控制台，看看有报错么
> 
> 不行吧，这个我按了F12没反应

Electron是alt打开菜单栏、ctrl+shift+i打开控制台

**Comment by ghost** [comment]
> > > > > 要不试试electron版本 https://github.com/ShirasawaSama/CefDetectorX
> > > > 
> > > > 
> > > > 然后它的也不行joy
> > > 
> > > 
> > > Electron版本可以打开控制台，看看有报错么
> > 
> > 
> > 不行吧，这个我按了F12没反应
> 
> Electron是alt打开菜单栏、ctrl+shift+i打开控制台
![图片](https://user-images.githubusercontent.com/32984303/205002240-3b2d02da-b39b-4b7c-ba64-58994f27266b.png)

**Comment by ShirasawaSama** [comment]
你没有安装Everything或者安装的是精简版Everything，readme里都有写

**Comment by ghost** [comment]
> 你没有安装Everything或者安装的是精简版Everything，readme里都有写

![图片](https://user-images.githubusercontent.com/32984303/205002563-6c35b627-8616-4331-8154-2e9167272771.png)
绝对是安装了，我还是一块前台运行

**Comment by ShirasawaSama** [comment]
> > 你没有安装Everything或者安装的是精简版Everything，readme里都有写
> 
> ![图片](https://user-images.githubusercontent.com/32984303/205002563-6c35b627-8616-4331-8154-2e9167272771.png) 绝对是安装了，我还是一块前台运行

也有可能是win7的everything不支持ipc吧

**Comment by ghost** [comment]
> > > 你没有安装Everything或者安装的是精简版Everything，readme里都有写
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/32984303/205002563-6c35b627-8616-4331-8154-2e9167272771.png) 绝对是安装了，我还是一块前台运行
> 
> 也有可能是win7的everything不支持ipc吧

我重新启动一下电脑看看吧，感觉不应该，都是支持win7的

**Comment by ghost** [comment]
> > > 你没有安装Everything或者安装的是精简版Everything，readme里都有写
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/32984303/205002563-6c35b627-8616-4331-8154-2e9167272771.png) 绝对是安装了，我还是一块前台运行
> 
> 也有可能是win7的everything不支持ipc吧

好了，莫名其妙成功了吧？
![图片](https://user-images.githubusercontent.com/32984303/205008503-8d52fe45-d19a-4153-8ea1-32eb3636cfc5.png)
