### ISSUE TITLE
加入去重

### ISSUE THREAD

**Issue by chiyuki0325** [ShirasawaSama/CefDetector#3]
在统计 cef 的时候，检查一下两个条目的 exe 是否在同一个文件夹，是的话就不用统计这条了
另外名字带 unins 的 (卸载程序) 也不用统计了

**Comment by ShirasawaSama** [comment]
是的 现在就是这个逻辑，现在带uninst\setup\report的不会被统计，或许可以改成unins.

另外第一个问题可能是是因为存在这样的结构

```
- chrome.exe
--- 102.22.22.1/v8_context_snapshot.bin
--- 103.33.33.1/v8_context_snapshot.bin
```

然后导致会有两份，这就是因为程序更新后没删旧版本出现的

**Comment by chiyuki0325** [comment]
是这样，这种算一份就行了
之所以用 unins 是因为有 unins0000.exe
wwww

**Comment by ShirasawaSama** [comment]
好的 下午改改，不过我更倾向于第一个问题显示到有v8_context_snapshot.bin的位置而不是exe

**Comment by chiyuki0325** [comment]
可执行文件的父目录相同就行了
另外，可以把 miniblink 也加入检测范围
https://github.com/weolar/miniblink49

**Comment by ShirasawaSama** [comment]
好的

**Comment by ShirasawaSama** [comment]
二代已加入去重和MINIBLINK检测功能: https://github.com/ShirasawaSama/CefDetectorX

**Comment by chiyuki0325** [comment]
用电子垃圾检测电子垃圾，屠龙者终将为龙是吧

**Comment by ShirasawaSama** [comment]
Added in [0.1.0](https://github.com/ShirasawaSama/CefDetector/releases/download/0.1.0/CefDetector.zip)
