### ISSUE TITLE
双击后无反应

### ISSUE THREAD

**Issue by LnksW** [ShirasawaSama/CefDetector#4]
版本：win10 22H2，已安装。net6和everything

**Comment by ShirasawaSama** [comment]
用.net3.0的试试 https://github.com/ShirasawaSama/CefDetector/releases/download/0.0.1/CefDetector.zip

**Comment by LnksW** [comment]
> 用.net3.0的试试 https://github.com/ShirasawaSama/CefDetector/releases/download/0.0.1/CefDetector.zip

说错了，使用3.0的没反应，使用6.0的会提示我安装6.0
![image](https://user-images.githubusercontent.com/42366809/204204080-8fc64934-0e1a-4bbf-bf31-0c21ceaa81aa.png)

**Comment by valetzx** [comment]
出现同款问题

![image](https://user-images.githubusercontent.com/45054400/204275889-26e56232-4503-4208-9333-74efee8d8f10.png)

**Comment by frg2089** [comment]
可能需要前往下载桌面运行时
https://dotnet.microsoft.com/zh-cn/download/dotnet/6.0
![image](https://user-images.githubusercontent.com/42184238/204287172-912038bf-a399-4129-bfc0-d936e30b0aae.png)

**Comment by ShirasawaSama** [comment]
使用Electron重写的二代: https://github.com/ShirasawaSama/CefDetectorX

**Comment by ShirasawaSama** [comment]
Duplicate #1
