### ISSUE TITLE
在？为什么不扫扫libcef.dll？

### ISSUE THREAD

**Issue by Gy4n** [ShirasawaSama/CefDetector#7]
一些兼容性好的应用（比如：网易云音乐）用的旧版本的`libcef.dll`
没有`v8_context_snapshot.bin`

**Comment by ShirasawaSama** [comment]
网易云音乐有 v8_context_snapshot.bin 啊

![image](https://user-images.githubusercontent.com/17093811/204255079-9e78e13d-38a1-4b74-9086-bbf093f56ffe.png)

**Comment by Gy4n** [comment]
哦，我更了一次新过后又更新了一次就有了😅

**Comment by Gy4n** [comment]
没事，uu也没有
![image](https://user-images.githubusercontent.com/69465873/204256930-c543e078-ccf8-492f-a3bf-c86f25966592.png)

**Comment by ShirasawaSama** [comment]
不扫 libcef.dll 的原因主要是因为 electron 就没有这玩意

**Comment by ShirasawaSama** [comment]
倒是可以考虑扫100_percent.pak这个文件

**Comment by Gy4n** [comment]
好像是`libcef.dll`大版本号是`3`的就没有这个玩意

**Comment by Gy4n** [comment]
> 好像是`libcef.dll`大版本号是`3`的就没有这个玩意

指`v8_context_snapshot.bin`

**Comment by ShirasawaSama** [comment]
二代扫描的是 `100_percent.pak`: https://github.com/ShirasawaSama/CefDetectorX

**Comment by ShirasawaSama** [comment]
Fixed in [0.1.0](https://github.com/ShirasawaSama/CefDetector/releases/download/0.1.0/CefDetector.zip)
